### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by dragonxtek** [Yoda12999/MyoBlueZ#1]
Hi, I'm trying to connect my MYO to your app, but when I start the application the following occurs:
./myo-bluez
Searching objects for myo
Myo found!
Connecting...
Connection failed: GDBus.Error:org.bluez.Error.InProgress: In Progress
(process:20674): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed

**Comment by yodaldevoid** [comment]
Yeah, that would be because when you tried it I was in the middle of a total rewrite. Try again and let me know how things go.

**Comment by dragonxtek** [comment]
I download your code again (it's important mention that you need to do a git clone --recursive).
When I run the program, it does nothing (no logs, no errors). How I can search my Myo?

**Comment by yodaldevoid** [comment]
Heya, sorry for the long wait for a response. I have removed the discovery functionality from the library as that really shouldn't be it's concern and it was just giving issues. The method to connect to your Myo is to select your Myo through whatever bluetooth interface you want to use (Blueman, bluetoothctl, etc.) and then run myo-bluez (or your own program for that matter). After you have connected to your Myo once through whatever interface you use, you should never have to do so again as myo-bluez will try to connect to Myos that Bluez remembers about.
