### ISSUE TITLE
customize main loop to read Myo data

### ISSUE THREAD

**Issue by stoxiri** [Yoda12999/MyoBlueZ#2]
Hi, thanks for sharing this.
I could run the program successfully. I now want to customise the main loop to for my application, that is reading and processing data from the Myo (EMG and orientation).
I suppose g_main_loop_run and some functions from your library are my starting point, but do not where to look. Would you brief me on how to get started?

**Comment by yodaldevoid** [comment]
Heya, sorry for the long wait. It is now possible to set callbacks to various events fired by the Myo. If you have any questions after looking at the code in myo-bluez_client.c please feel free to ask!
